### ISSUE TITLE
object_detection/protos/*.proto: No such file or directory

### ISSUE THREAD

**Issue by mirage07** [IBM/augment-visual-recognition-detection-of-low-resolution-human-faces#4]
while executing 2.3, i encountered the object_detection/protos/*.proto: No such file or directory error. 

I have already upload object_detection.zip. 

2.1 (adding IBM storage credentials is done with no error while running)
2.2 (Extracting the zip file has no issues too)
2.3 object_detection/protos/*.proto: No such file or directory

Please help me as I need to submit my codes for call for code. 
![error](https://user-images.githubusercontent.com/43549398/58246497-c9bb5600-7d89-11e9-8afa-e06de9e1c7da.jpg)

**Comment by smruthi33** [comment]
Hi, I have you restarted the kernel?

**Comment by mirage07** [comment]
> Hi, I have you restarted the kernel?

Yes restarted many times. It just kept giving me this issue.

**Comment by smruthi33** [comment]
Have you added the preferred Model as given in Step 4.2 https://github.com/IBM/augment-visual-recognition-detection-of-low-resolution-human-faces#42-model-preparation

**Comment by smruthi33** [comment]
There might be an issue in the way the file was unzipped, can you pls run an `ls` command on one of your notebook cells? And pls ensure the directory structure follows object_detection/proto... If not this will cause errors. 

Sometimes, an additional wrapper folder gets created while unzipping. In that case, you can run cd `your_folder_name`

**Comment by smruthi33** [comment]
You can directly use cd `folder_name`. As given in this link- https://dataplatform.cloud.ibm.com/exchange/public/entry/view/133dfc4cd1480bbe4eaa78d3f6d84396
You can try this instead of adding object_detection twice... It will really mess with the paths

**Comment by mirage07** [comment]
Hi,

I managed to pass the protoc issue now, but i have this importError now which states my tensorflow verison is 1.9 or lower. i actually pip install version 1.10 but it still gives me the same error. 

Please help me to look into this and advice.


![error](https://user-images.githubusercontent.com/43549398/58456648-4cac2a00-8157-11e9-9e20-63db2ef307b0.jpg)

**Comment by smruthi33** [comment]
Hi @mirage07,

The packages that are used here require a stable Tensorflow version. Hence, I have included a check allowing only Version 1.9 and below. Can you install version 1.9 Tensorflow? As given in the notebook in Line 2, under the Tensorflow Installation section. Also, pls be sure to restart your kernel before resuming with the rest of the execution.
