### ISSUE TITLE
NodeDef mentions attr 'data_format' not in Op

### ISSUE THREAD

**Issue by krishnac7** [IBM/augment-visual-recognition-detection-of-low-resolution-human-faces#5]
'ssd_mobilenet_v1_coco' model gives an error NodeDef mentions attr 'data_format' not in Op

using http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz model fixes it

**Comment by smruthi33** [comment]
Okay, you can use any object_detection model to be used.
